#!/bin/bash
# ----------------------------------------------------------------------------
# "THE BEER-WARE LICENSE" (Revision 42):
# <pntanasis@gmail.com> wrote this file. As long as you retain this notice you
# can do whatever you want with this stuff. If we meet some day, and you think
# this stuff is worth it, you can buy me a beer in return Periklis Ntanasis
# ----------------------------------------------------------------------------
#
# This is a bash script for automating the installation of the programs
# that we need for our university projects.
#

## TODO check needed progs | build pkgs | print status

## Environment
BUILD_DIR="/tmp/src/"
BUILD_FLAGS="--prefix=/usr LDFLAGS=\"-Wl,--no-as-needed\""

## Package Managers
PMS=(	[ubuntu]="apt-get install" 
		[arch]="pacman -S" )

## Applications throught the PMS
apps=(	[common]="netbeans scilab geany nmap spim tcsh"
		[ubuntu]="openjdk-6-jdk build-essential"
		[arch]="openjdk6 base-devel" )

## Applications that need to be built from source
## FIXME need to be rethinked
LAMPP="http://www.apachefriends.org/download.php?xampp-linux-1.7.3a.tar.gz"
OMNET="http://www.omnetpp.org/omnetpp/doc_download/2217-omnet-41-source--ide-tgz"
# ACCEPT THE AGREEMENT
NESSUS="http://www.nessus.org/download/index.php?product=nessus42-linux"
# register to download Quartus
QUARTUS="https://www.altera.com/servlets/download3?swcode=WWW-SWD-QII-WE-100SP1-LNX&l=en"

## Usage message
function usage() {
cat << EOF
usage: ($basename $0) [options]

	Options are:
	-d	distribution	the user's distro name [supported: arch, ubuntu]
	-i					install all applications
	-r					remove all applications

EOF
}

## FIXME Extract an archive
function extract() {
	// code //
}

## FIXME Build a package from source
function buildpkg() {
	mkdir -p $BUILD_DIR
	cd $BUILD_DIR
	wget $pkg_url
	extract $pkg
	./configure --${CONF_FLAGS}
	make && make install
}

## Install a package using PMS
function installpkgs() {	
	${PMS[$distro]} ${apps["common"]} ${apps[$distro]}
}

## FIXME Main run 
while getopts "d:b:ar" flag
do
	case $flag in
		d )	distro="$OPTARG"
			if [ "$distro" != "ububtu" -o  "$distro" != "arch" ]
			then
				usage && exit 1
			fi ;;
		b ) BUILD_DIR=$OPTARG ;;
		a ) remove=1 && install=0 ;;
		r ) remove=1 && install=0 ;;
		* ) usage && exit 1 ;;
	esac
done

# ---------------------------------------------------------
#  # apt
# apt="apt"
# if [ $PKGMNGR = $apt ]; then
# 	pkg=$BUILD" "$JAVA" "$NETBEANS" "$SCILAB" "$GEANY" "$NMAP" "$CSH" "$SPIM
# 	apt-get update
# 	apt-get install $pkg
# fi
# 
# # pacman
# 
# # The downloads/compilation part!
# cd /tmp
# 
# # LAMPP installation
# wget $LAMPPurl
# tar xvfz xampp-linux-1.7.3a.tar.gz -C /opt
# 
# # OMNET++ installation
# wget $OMNETurl
# tar xvfz 2217-omnet-41-source--ide-tgz -C /opt
# echo "export PATH=/opt/omnetpp-4.1/bin">>/etc/bash.bashrc
# /opt/omnetpp-4.1/configure
# make MODE=release
# 
# if [ $1 = $arch ]; then
# 
# 	# SPIM installation
# 
# 	wget $SPIMurl
# 	tar xvfz spim.tar.gz
# 	spim-8.0/spim/make install
# fi 

